swagger: "2.0"
info:
  description: "This service manages the swagger specifications. It stores all static and dynamically generated swagger specifications from the repositories and services."
  version: "1.0.0"
  title: "Swagger"
host: "api.sepl.infai.org"
basePath: "/swagger"
schemes:
- "https"
paths:
  /:
    get:
      tags:
      - "Get all swagger specifications filtered by your permissions"
      summary: ""
      description: ""
      produces:
      - "application/json"
      responses:
        200:
          description: "Return swagger specifications"
          schema: 
            items: 
              $ref: "#/definitions/Swagger" 
            type: "array"
definitions: 
  Swagger: 
    type: "object"
